server :
  servlet :
    context-path : /
spring :
  resources:
    static-locations: classpath:/resources,classpath:/static
    # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  mvc:   #静态文件
    static-path-pattern : /static/**
  #模板引擎
  thymeleaf:
    model: HTML5
    prefix: classpath:/templates/
    suffix: .html
    #指定编码
    encoding: utf-8
    #禁用缓存 默认false
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  datasource:
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root}
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/quick_link_0?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&useTimezone=true&serverTimezone=GMT
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 120000
      idle-timeout: 60000
      connection-timeout: 30000
      maximum-pool-size: 32
      minimum-idle: 10


